# Generated by Django 4.1 on 2023-03-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('surname', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('cell', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('id_or_passport', models.CharField(max_length=256)),
                ('academic_year', models.CharField(max_length=64)),
                ('degree_or_major', models.CharField(max_length=128)),
                ('Accounting', models.CharField(default='NA', max_length=3)),
                ('Afrikaans_Second_Language', models.CharField(default='NA', max_length=3)),
                ('Biology_or_Life_Sciences', models.CharField(default='NA', max_length=3)),
                ('Business', models.CharField(default='NA', max_length=3)),
                ('Chemistry', models.CharField(default='NA', max_length=3)),
                ('Economics', models.CharField(default='NA', max_length=3)),
                ('English', models.CharField(default='NA', max_length=3)),
                ('Geography', models.CharField(default='NA', max_length=3)),
                ('History', models.CharField(default='NA', max_length=3)),
                ('ICT', models.CharField(default='NA', max_length=3)),
                ('isiXhosa', models.CharField(default='NA', max_length=3)),
                ('Mathematics', models.CharField(default='NA', max_length=3)),
                ('Mathematics_AP', models.CharField(default='NA', max_length=3)),
                ('Physical_Sciences', models.CharField(default='NA', max_length=3)),
                ('Other_1', models.CharField(default='NA', max_length=256)),
                ('Other_2', models.CharField(default='NA', max_length=256)),
            ],
        ),
    ]
